name: ekhoncharge
description: A new Flutter project.
publish_to: 'none'
version: 2.0.0+7

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #Our dependencies/packages
  get: ^4.6.5
  dio: ^5.2.1+1
  shared_preferences: ^2.2.0
  file_picker: ^5.3.2
  font_awesome_flutter: ^10.5.0
  local_auth: ^2.1.6
  fluttertoast: ^8.2.2
  image_picker: ^1.0.1
  image_cropper: ^5.0.0
  webview_flutter: ^4.2.2
  qr_code_scanner: ^1.0.1
  percent_indicator: ^4.2.2

  curved_nav_bar: ^0.0.2
  flutter_easyloading: ^3.0.5
  flutter_native_image: ^0.0.6
  pusher_channels_flutter: ^2.2.0
  flutter_rating_bar: ^4.0.1
  gender_picker: ^1.0.2
  photo_view: ^0.14.0
  date_format: ^2.0.0
  connectivity_plus: ^5.0.2
  lottie: ^2.7.0
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.5.3

  upgrader: 9.0.0
  url_launcher: ^6.2.6
  geolocator: ^11.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/mapImages/
    - assets/icons/
    - assets/stationImages/
    - assets/animations/
    - .git/HEAD

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
