var nearbyChargers = {
  "success": true,
  "chargers": [
    {
      "charger_id": 100001,
      "name": "Ekhon Charge Uttara",
      "endpoint_address": "charger-points-1",
      "ocpp_protocol": "ocpp2.0",
      "registration_status": "unregistered",
      "charge_point_vendor": "vendor-456",
      "charge_point_model": "DH-DC0800HG60-K",
      "charge_point_serial_number": "TESLA-AB-PMIL-02",
      "charge_box_serial_number": "SL-109035",
      "fw_version": "2.1.0.0.7b102",
      "fw_update_status": "Pending",
      "fw_update_timestamp": "2023-08-07 15:30:45",
      "iccid": 13,
      "arrived_hour": "22:15",
      "distance": 7,
      "distanceUnit": "miles",
      "is_fav": true,
      "imsi": "EcoCharge",
      "meter_type": "Smart Meter",
      "meter_serial_number": 129564,
      "diagnostics_status": "Some Issues",
      "diagnostics_timestamp": "2023-08-07 20:30:45",
      "last_heartbeat_timestamp": "2023-08-07 16:30:45",
      "description": "Charging in progress",
      "note": "Please wait for completion",
      "location_latitude": 24.24,
      "location_longitude": 91.24,
      "charging_type": "DC,AC, Slow Charging",
      "total_ports": 10,
      "available_ports": 4,
      "photo": "assets/stationImages/echargestaion3.jpeg",
      "created_at": "2023-07-07 11:30:22",
      "updated_at": "2023-07-07 11:30:22"
    },
    {
      "charger_id": 100002,
      "name": "Ekhon Charge Dhanmondi",
      "endpoint_address": "charger-points-2",
      "ocpp_protocol": "ocpp2.0",
      "registration_status": "registered",
      "charge_point_vendor": "vendor-789",
      "charge_point_model": "DH-DC0900HG72-L",
      "charge_point_serial_number": "NISSAN-CD-PMIL-03",
      "charge_box_serial_number": "SL-109036",
      "fw_version": "2.2.0.0.8b103",
      "fw_update_status": "Up to Date",
      "fw_update_timestamp": "2023-08-08 11:20:35",
      "iccid": 14,
      "arrived_hour": "19:45",
      "distance": 9,
      "distanceUnit": "miles",
      "is_fav": false,
      "imsi": "EcoCharge Plus",
      "meter_type": "Digital Meter",
      "meter_serial_number": 129565,
      "diagnostics_status": "All Okay",
      "diagnostics_timestamp": "2023-08-08 15:20:35",
      "last_heartbeat_timestamp": "2023-08-08 12:20:35",
      "description": "Ready for charging",
      "note": "Enjoy your charging experience",
      "location_latitude": 25.25,
      "location_longitude": 92.25,
      "charging_type": "DC,AC, Fast Charging",
      "total_ports": 15,
      "available_ports": 8,
      "photo": "assets/stationImages/echargestation2.jpg",
      "created_at": "2023-07-08 14:15:45",
      "updated_at": "2023-07-08 14:15:45"
    },
    {
      "charger_id": 100003,
      "name": "Ekhon Charge Gulshan",
      "endpoint_address": "charger-points-3",
      "ocpp_protocol": "ocpp2.0",
      "registration_status": "registered",
      "charge_point_vendor": "vendor-101",
      "charge_point_model": "DH-DC1000HG80-M",
      "charge_point_serial_number": "FORD-EF-PMIL-04",
      "charge_box_serial_number": "SL-109037",
      "fw_version": "2.3.0.0.9b104",
      "fw_update_status": "Pending",
      "fw_update_timestamp": "2023-08-09 09:10:55",
      "iccid": 15,
      "arrived_hour": "18:30",
      "distance": 8,
      "distanceUnit": "miles",
      "is_fav": true,
      "imsi": "EcoCharge Pro",
      "meter_type": "Smart Meter",
      "meter_serial_number": 129566,
      "diagnostics_status": "All Okay",
      "diagnostics_timestamp": "2023-08-09 14:10:55",
      "last_heartbeat_timestamp": "2023-08-09 10:10:55",
      "description": "Charging station available",
      "note": "Stay charged and go green",
      "location_latitude": 26.26,
      "location_longitude": 93.26,
      "charging_type": "DC,AC, Slow Charging",
      "total_ports": 12,
      "available_ports": 6,
      "photo": "assets/stationImages/echargestation6.jpeg",
      "created_at": "2023-07-09 10:25:30",
      "updated_at": "2023-07-09 10:25:30"
    },
    {
      "charger_id": 100004,
      "name": "Ekhon Charge Mirpur",
      "endpoint_address": "charger-points-4",
      "ocpp_protocol": "ocpp2.0",
      "registration_status": "unregistered",
      "charge_point_vendor": "vendor-202",
      "charge_point_model": "DH-DC1100HG96-X",
      "charge_point_serial_number": "TOYOTA-GH-PMIL-05",
      "charge_box_serial_number": "SL-109038",
      "fw_version": "2.4.0.0.10b105",
      "fw_update_status": "Pending",
      "fw_update_timestamp": "2023-08-10 08:40:20",
      "iccid": 16,
      "arrived_hour": "17:00",
      "distance": 10,
      "distanceUnit": "miles",
      "is_fav": false,
      "imsi": "GreenCharge",
      "meter_type": "Digital Meter",
      "meter_serial_number": 129567,
      "diagnostics_status": "Some Issues",
      "diagnostics_timestamp": "2023-08-10 13:40:20",
      "last_heartbeat_timestamp": "2023-08-10 09:40:20",
      "description": "Charging station ready",
      "note": "Please report any issues",
      "location_latitude": 27.27,
      "location_longitude": 94.27,
      "charging_type": "DC,AC, Fast Charging",
      "total_ports": 18,
      "available_ports": 7,
      "photo": "assets/stationImages/echargestation4.jpeg",
      "created_at": "2023-07-10 13:55:10",
      "updated_at": "2023-07-10 13:55:10"
    },
    {
      "charger_id": 100005,
      "name": "Ekhon Charge Banani",
      "endpoint_address": "charger-points-5",
      "ocpp_protocol": "ocpp2.0",
      "registration_status": "registered",
      "charge_point_vendor": "vendor-303",
      "charge_point_model": "DH-DC1200HG108-Y",
      "charge_point_serial_number": "CHEVY-IJ-PMIL-06",
      "charge_box_serial_number": "SL-109039",
      "fw_version": "2.5.0.0.11b106",
      "fw_update_status": "Up to Date",
      "fw_update_timestamp": "2023-08-11 14:55:30",
      "iccid": 17,
      "arrived_hour": "16:30",
      "distance": 12,
      "distanceUnit": "miles",
      "is_fav": false,
      "imsi": "OasisCharge",
      "meter_type": "Smart Meter",
      "meter_serial_number": 129568,
      "diagnostics_status": "All Okay",
      "diagnostics_timestamp": "2023-08-11 18:55:30",
      "last_heartbeat_timestamp": "2023-08-11 15:55:30",
      "description": "Charging station available",
      "note": "Enjoy your charging time",
      "location_latitude": 28.28,
      "location_longitude": 95.28,
      "charging_type": "DC,AC, Fast Charging",
      "total_ports": 14,
      "available_ports": 9,
      "photo": "assets/stationImages/echargestation5.jpeg",
      "created_at": "2023-07-11 08:30:15",
      "updated_at": "2023-07-11 08:30:15"
    },
    {
      "charger_id": 100006,
      "name": "Ekhon Charge Mohammadpur",
      "endpoint_address": "charger-points-6",
      "ocpp_protocol": "ocpp2.0",
      "registration_status": "unregistered",
      "charge_point_vendor": "vendor-404",
      "charge_point_model": "DH-DC1300HG120-Z",
      "charge_point_serial_number": "JAGUAR-KL-PMIL-07",
      "charge_box_serial_number": "SL-109040",
      "fw_version": "2.6.0.0.12b107",
      "fw_update_status": "Pending",
      "fw_update_timestamp": "2023-08-12 10:10:40",
      "iccid": 18,
      "arrived_hour": "20:45",
      "distance": 15,
      "distanceUnit": "miles",
      "is_fav": true,
      "imsi": "PowerCharge Pro",
      "meter_type": "Digital Meter",
      "meter_serial_number": 129569,
      "diagnostics_status": "Some Issues",
      "diagnostics_timestamp": "2023-08-12 16:10:40",
      "last_heartbeat_timestamp": "2023-08-12 11:10:40",
      "description": "Charging station ready",
      "note": "Please report any issues",
      "location_latitude": 29.29,
      "location_longitude": 96.29,
      "charging_type": "DC,AC, Slow Charging",
      "total_ports": 16,
      "available_ports": 6,
      "photo": "assets/stationImages/echargestation6.jpeg",
      "created_at": "2023-07-12 09:15:55",
      "updated_at": "2023-07-12 09:15:55"
    },
    {
      "charger_id": 100007,
      "name": "Ekhon Charge Jatrabari",
      "endpoint_address": "charger-points-7",
      "ocpp_protocol": "ocpp2.0",
      "registration_status": "registered",
      "charge_point_vendor": "vendor-505",
      "charge_point_model": "DH-DC1400HG132-W",
      "charge_point_serial_number": "VOLVO-MN-PMIL-08",
      "charge_box_serial_number": "SL-109041",
      "fw_version": "2.7.0.0.13b108",
      "fw_update_status": "Integrated Circuit",
      "fw_update_timestamp": "2023-08-13 12:25:50",
      "iccid": 19,
      "arrived_hour": "19:30",
      "distance": 20,
      "distanceUnit": "miles",
      "is_fav": false,
      "imsi": "EcoCharge Ultimate",
      "meter_type": "Smart Meter",
      "meter_serial_number": 129570,
      "diagnostics_status": "All Okay",
      "diagnostics_timestamp": "2023-08-13 15:25:50",
      "last_heartbeat_timestamp": "2023-08-13 13:25:50",
      "description": "Ready for charging",
      "note": "Enjoy eco-friendly charging",
      "location_latitude": 30.30,
      "location_longitude": 97.30,
      "charging_type": "DC,AC, Fast Charging",
      "total_ports": 14,
      "available_ports": 7,
      "photo": "assets/stationImages/echargestation2.jpg",
      "created_at": "2023-07-13 14:40:25",
      "updated_at": "2023-07-13 14:40:25"
    },
    {
      "charger_id": 100008,
      "name": "Ekhon Charge Baridhara",
      "endpoint_address": "charger-points-8",
      "ocpp_protocol": "ocpp2.0",
      "registration_status": "registered",
      "charge_point_vendor": "vendor-606",
      "charge_point_model": "DH-DC1500HG144-U",
      "charge_point_serial_number": "PORSCHE-OP-PMIL-09",
      "charge_box_serial_number": "SL-109042",
      "fw_version": "2.8.0.0.14b109",
      "fw_update_status": "Up to Date",
      "fw_update_timestamp": "2023-08-14 11:15:55",
      "iccid": 20,
      "arrived_hour": "18:15",
      "distance": 18,
      "distanceUnit": "miles",
      "is_fav": false,
      "imsi": "QuickCharge Pro",
      "meter_type": "Digital Meter",
      "meter_serial_number": 129571,
      "diagnostics_status": "All Okay",
      "diagnostics_timestamp": "2023-08-14 15:15:55",
      "last_heartbeat_timestamp": "2023-08-14 12:15:55",
      "description": "Charging station available",
      "note": "Quick and efficient charging",
      "location_latitude": 31.31,
      "location_longitude": 98.31,
      "charging_type": "DC,AC, Fast Charging",
      "total_ports": 16,
      "available_ports": 9,
      "photo": "assets/stationImages/echargestaion3.jpeg",
      "created_at": "2023-07-14 12:50:35",
      "updated_at": "2023-07-14 12:50:35"
    },
    {
      "charger_id": 100009,
      "name": "Ekhon Charge Pallabi",
      "endpoint_address": "charger-points-9",
      "ocpp_protocol": "ocpp2.0",
      "registration_status": "unregistered",
      "charge_point_vendor": "vendor-707",
      "charge_point_model": "DH-DC1600HG156-V",
      "charge_point_serial_number": "NIKOLA-PQ-PMIL-10",
      "charge_box_serial_number": "SL-109043",
      "fw_version": "2.9.0.0.15b110",
      "fw_update_status": "Pending",
      "fw_update_timestamp": "2023-08-15 09:30:40",
      "iccid": 21,
      "arrived_hour": "21:00",
      "distance": 22,
      "distanceUnit": "miles",
      "is_fav": true,
      "imsi": "GreenCharge Max",
      "meter_type": "Smart Meter",
      "meter_serial_number": 129572,
      "diagnostics_status": "Some Issues",
      "diagnostics_timestamp": "2023-08-15 16:30:40",
      "last_heartbeat_timestamp": "2023-08-15 10:30:40",
      "description": "Charging station ready",
      "note": "Please report any issues",
      "location_latitude": 32.32,
      "location_longitude": 99.32,
      "charging_type": "DC,AC, Slow Charging",
      "total_ports": 14,
      "available_ports": 6,
      "photo": "assets/stationImages/echargestation4.jpeg",
      "created_at": "2023-07-15 10:45:20",
      "updated_at": "2023-07-15 10:45:20"
    },
    {
      "charger_id": 100010,
      "name": "Ekhon Charge Shyamoli",
      "endpoint_address": "charger-points-10",
      "ocpp_protocol": "ocpp2.0",
      "registration_status": "registered",
      "charge_point_vendor": "vendor-808",
      "charge_point_model": "DH-DC1700HG168-Q",
      "charge_point_serial_number": "FERRARI-RS-PMIL-11",
      "charge_box_serial_number": "SL-109044",
      "fw_version": "2.10.0.0.16b111",
      "fw_update_status": "Integrated Circuit",
      "fw_update_timestamp": "2023-08-16 08:20:25",
      "iccid": 22,
      "arrived_hour": "22:45",
      "distance": 25,
      "distanceUnit": "miles",
      "is_fav": false,
      "imsi": "PowerCharge Ultimate",
      "meter_type": "Digital Meter",
      "meter_serial_number": 129573,
      "diagnostics_status": "All Okay",
      "diagnostics_timestamp": "2023-08-16 14:20:25",
      "last_heartbeat_timestamp": "2023-08-16 09:20:25",
      "description": "Ready for charging",
      "note": "Enjoy fast and reliable charging",
      "location_latitude": 33.33,
      "location_longitude": 100.33,
      "charging_type": "DC,AC, Fast Charging",
      "total_ports": 16,
      "available_ports": 9,
      "photo": "assets/stationImages/echargestation5.jpeg",
      "created_at": "2023-07-16 14:35:45",
      "updated_at": "2023-07-16 14:35:45"
    }
  ]
};
