import 'package:ekhoncharge/constants/app_constants.dart';

const Map<String, String> bn = {
  eAppName: 'Ekhon Charge',
  eAppVersionTxt: '২.০.০',
  eLoginTxt: 'প্রবেশ করুন',
  eSignupTxt: 'নিবন্ধন করুন',
  eDioCancelError: 'এপিআই সার্ভারের সাথে সংযোগের সময়সীমা শেষ হয়েছে',
  eReceiveTimeout: 'এপিআই সার্ভারের সাথে সংযোগের সময়সীমা শেষ হয়েছে',
  sendTimeout: 'এপিআই সার্ভারের সাথে সংযোগের সময়সীমা শেষ হয়েছে',
  eNoInternet: 'ইন্টারনেট সংযোগের কারণে এপিআই সার্ভারে সংযোগ ব্যর্থ হয়েছে৷',
  eSomethingWrong: 'Oops something went wrong',
  eSessionExpiredMszTxt:
      'আপনার সেশনের মেয়াদ শেষ হয়েছে, অনুগ্রহ করে লগইন করুন',
  eOverview: 'হোম',
  eStation: 'স্টেশন',
  eWalletTxt: 'ওয়ালেট ',
  eQrScanTxt: 'QR',
  eNotificationTxt: 'বিজ্ঞপ্তি',
  eMenu: 'মেনু',
  eProfile: 'প্রোফাইল',
  eSetting: 'সেটিং',
  ePaymentPlans: 'পেমেন্ট এবং প্লেন ',
  eEditProfile: 'এডিট প্রোফাইল',
  ePremiumOffers: 'প্রিমিয়াম অফার',
  eAddPromoCode: 'প্রমো কোড যোগ করুন',
  eChargingFAQ: 'চার্জিং FAQ',
  ePrivacyLegacy: 'প্রাইভেসি এবং উত্তরাধিকার',
  eContactUs: 'যোগাযোগ করুন',
  eAppVersion: 'অ্যাপ ভার্সন ',
  eLogoutTxt: 'লগ আউট ',
  eAddAnotherCar: 'আরেকটি গাড়ি যোগ করুন',

  //*****OverViewPage******//
  eTapForBalance: 'ব্যালেন্স',
  eChargingHistory: 'চার্জিং হিস্টোরি',
  eMyCar: 'আমার গাড়ি',
  eMyECharge: 'আমার ই চার্জ',
  eOffers: 'অফার',
  eMyOffer: 'আমার অফার',
  eSendMoney: 'টাকা পাঠানো',
  eGpOffer: 'জিপি অফার',
  eOrderFood: 'অর্ডার ফুড ',

  //****Wallet Page******//
  eBalance: 'ব্যালেন্স ',
  eTk: ' টাকা ',
  eMyWallet: 'আমার ওয়ালেট',
  eReceive: 'অর্থ গ্রহণ',
  ePayment: 'অর্থ প্রদান',
  eAddMoney: 'এড মানি',
  eTransactionHistory: 'ট্রানজেকশন হিস্টোরি',
  eNoTransactionHistory: 'কোন ট্রানজেকশন হিস্টোরি নাই ',

//****Station Nearby Page******//
  eStationNearby: 'নিকটবর্তী স্টেশন',
  eOops: 'ওহো দুঃখিত',
  eNoConnectorAvailable: 'কোন কানেক্টর এভেলেবেল নেই',
  eAvailableCharger: 'এভেলেবল চার্জার',
  ePowerCapacity: 'পাওয়ার ক্যাপাসিটি',

//****Profile Nav Page******//

  eRegisteredCarDetails: 'নিবন্ধিত গাড়ির বিবরণ',
  eChangePassword: 'পাসওয়ার্ড পরিবর্তন করুন',
  eExploreStations: 'স্টেশন অন্বেষণ করুন',
  eDeleteAccount: 'অ্যাকাউন্ট মুছে ফেলুন',

//****Change Password Page******//

  eOldPassword: 'পুরাতন পাসওয়ার্ড',
  eNewPassword: 'নতুন পাসওয়ার্ড',
  eReTypeNewPassword: 'নতুন পাসওয়ার্ড পুনরায় লিখুন',
  eSubmit: 'জমা দিন ',

//****Forgot Password Section******//

  eForgotPassword: 'পাসওয়ার্ড ভুলে গেছেন',
  eForgotPasswordDescription:
      "আপনি যদি আপনার পাসওয়ার্ড ভুলে গিয়ে থাকেন, চিন্তা করবেন না। নীচে আপনার ফোন নম্বর লিখুন এবং আমরা আপনাকে এটি পুনরায় সেট করতে সাহায্য করব",
  eNewPasswordDescription:
      "আপনার অ্যাকাউন্টের জন্য একটি নতুন পাসওয়ার্ড তৈরি করুন। আপনার পাসওয়ার্ড আপনার আগের থেকে আলাদা হতে হবে",
  ePhoneVerifyDescription:
      "আমরা আপনার ফোন নম্বরে একটি যাচাইকরণ ৪ সংখ্যার কোড পাঠিয়েছি। ফোন যাচাইকরণ প্রক্রিয়া সম্পূর্ণ করতে কোড লিখুন",
  eEnterYourPhoneNumber: "আপনার ফোন নম্বর লিখুন",
  eVerifyYourPhoneNumber: "ফোন নম্বর যাচাই করুন",

  //****Registered car Page******//
  eRegisteredVehicleDetails: "নিবন্ধিত গাড়ির বিবরণ",
  eMax: " সর্বোচ্চ",
  eTime: " সময়",
  eModel: " মডেল",
  eTotalPower: "সমস্ত ক্ষমতা",
  eTotalTorque: "মোট টর্ক",
  eTopSpeed: "সর্বোচ্চ গতি",
  eElectricRange: "বৈদ্যুতিক রেঞ্জ",
  eChargerPort: "চার্জার পোর্ট",
  eEngine: "ইঞ্জিন",
  eRemoveCar: "গাড়ি মুছে দিন",
  eConfirmation: "আপনি কি নিশ্চিত?",
  eConfirmMessage: "আপনি কি একেবারে নিশ্চিত যে আপনি এই গাড়িটি সরাতে চান",
  eOnlyCarRemoveMessage: "আপনি আপনার একমাত্র গাড়ী সরাতে পারবেন না",

  //****Payment Section******//
  eMobileBanking: "মোবাইল ব্যাংকিং",
  eCard: "কার্ড",
  eBkash: "বিকাশ",
  eNagad: "নগদ",
  eRocket: "রকেট",
  eAddMoneySource: " আপনার অর্থ উৎস নির্বাচন করুন",
  eBankToMyWallet: " ব্যাংক টু মাই ওয়ালেট",
  eCardToMyWallet: " কার্ড টু মাই ওয়ালেট",
  eSelectDebitCardToAddMoney:
      " বিনামূল্যে টাকা যোগ করতে ডেবিট/এটিএম কার্ড নির্বাচন করুন ",
  eMaster: "মাস্টার",
  eMasterCard: "মাস্টার কার্ড",
  eVISA: "ভিসা",
  eCardPayment: "কার্ড পেমেন্ট",
  eAccountNumber: "  একাউন্ট নাম্বার ",
  eEnterAmount: " পরিমান লিখুন ",
  eEnterMoreThan50Tk: "৫০ টাকার বেশি লিখুন",
  eOk: "ওকে",
  eAddMoneyBkash: "বিকাশ এড মানি করুন",
  eUser: "বিব্যবহারকারী",
  eAmount: "অ্যামাউন্ট ",
  eCheckout: "চেকআউট ",

  //****Validation Section******//

  eValidationError: 'অনুমোদন ত্রুটি',
  eFillNameField: 'অনুগ্রহ করে নামের ফিল্ড পূরণ করুন ',
  eFillEmailField: 'অনুগ্রহ করে ইমেইলের ফিল্ড পূরণ করুন ',
  eFillPhoneField: 'অনুগ্রহ করে ফোনের ফিল্ড পূরণ করুন ',
  eFillPasswordField: 'অনুগ্রহ করে পাসওয়ার্ডের ফিল্ড পূরণ করুন',
  eFillRePasswordField: 'অনুগ্রহ করে পুনরায় পাসওয়ার্ডের ফিল্ড পূরণ করুন',
  eNameThreeCharacter: 'নাম অবশ্যই অন্তত ৩ টি অক্ষরের হতে হবে.',
  eEnterValidEmail: 'দয়া করে একটি বৈধ ইমেইল এড্রেস লিখুন',
  eNumberElevenDigit: 'ফোন নম্বর অবশ্যই ১১ সংখ্যার হতে হবে',
  ePasswordEightDigit: 'পাসওয়ার্ড অবশ্যই অন্তত ৮ টি অক্ষরের হতে হবে',
  eConfirmPasswordEightDigit:
      'কনফার্ম পাসওয়ার্ড অবশ্যই অন্তত ৮ টি অক্ষরের লম্বা হতে হবে',
  ePasswordAndConfirmPasswordSame:
      'পাসওয়ার্ড এবং কনফার্ম পাসওয়ার্ড মিলতে হবে',
  eEnterOtp: 'দয়া করে OTP লিখুন',

  eEnterEmail: 'দয়া করে আপনার ইমেইল লিখুন',
  eEnterPassword: 'দয়া করে আপনার পাসওয়ার্ড লিখুন',

//****Station Section******//

  eAmenities: 'সুযোগ-সুবিধা',
  // ePayment: 'পেমেন্ট',
  eChargers: 'চার্জার',
  eNoChargerDataAvailableTxt: 'চার্জার তথ্য পাওয়া যায়নি',
  eMaxCapacityTxt: 'সর্বোচ্চ ধারণক্ষমতা',
  ePerKWTxt: 'প্রতি KW',
  eNoChargerAreSelectedTxt: 'কোন চার্জার নির্বাচিত হয়নি',
  eNoConnectorAreSelectedTxt: 'কোন কানেক্টর নির্বাচিত হয়নি',
  eLocationCoordinatesAreNotAvailableTxt: 'অবস্থানের স্থানাঙ্ক পাওয়া যায়নি',
  eThisStationisSuitablewithAllofYourVehiclesTxt:
      'এই স্টেশনটি আপনার সকল গাড়ির জন্য উপযুক্ত',
  eConnector: 'কানেক্টর',
  eDirection: 'ডাইরেকশন',
  eError: 'ত্রুটি',
  eBack: 'পিছনে',
  eAreYouSureTxt: 'আপনি কি নিশ্চিত?',
  eDeleteTxt: 'আপনার অ্যাকাউন্ট মুছে ফেলার ফলে আপনার সমস্ত ডেটা, সেটিংস এবং সংশ্লিষ্ট তথ্য স্থায়ীভাবে হারিয়ে যাবে',
  eDeleteAccountTxt2: 'আপনি কি নিশ্চিত যে আপনি আপনার অ্যাকাউন্টটি মুছতে চান? এই অ্যাকশনটি পুনরুদ্ধার করা যাবে না ',
  eDeleteAccountTxt: 'অ্যাকাউন্ট মুছে ফেলুন',
  eDeleteBtnTxt: 'অ্যাকাউন্ট মুছে ফেলুন',
  eCancel: 'বাতিল করুন',
  eBookSlot: 'স্লট বুক',
  ePhoneNumber: 'ফোন নাম্বার',
  ePhoneNumberText: 'এই স্টেশনের জন্য ফোন নাম্বার পাওয়া যায় নি',
  eRatingAndReview: 'রেটিং এবং পর্যালোচনা',
  eNotSelectChargerAndConnector: 'আপনি চার্জার এবং কানেক্টর নির্বাচন করেননি',
  eNotSelectChargerTxt: 'আপনি চার্জার নির্বাচন করেননি',
  eNotSelectConnectorTxt: 'আপনি কানেক্টর নির্বাচন করেননি',

  eWalletCreatingTxt: 'আপনার ওয়ালেট তৈরি হচ্ছে ...',
  eAddVehiclesTxt:
      'আপনার গাড়িটি সামঞ্জস্যপূর্ণ চার্জিং স্টেশনগুলি খুঁজে পাবে৷ বিস্তারিত তথ্য প্রদানের জন্য ট্যাপ করুন',
  eAddVehicleButton: 'অ্যাড গাড়ি',
  eViewingCar: 'গাড়ি দেখা',
  eSelectCar: 'গাড়ি নির্বাচন করুন',
  eChooseYourMachineTxt:
      'আপনার গাড়িটি এখন চার্জের সাথে কীভাবে সংযুক্ত করা হবে তা নির্বাচন করুন',
  eChooseMakeCarTxt: 'ব্র্যান্ড নির্বাচন করুন',
  eChooseModelCarTxt: 'মডেল নির্বাচন করুন',
  eChooseYearCarTxt: 'সাল নির্বাচন করুন"',
  eReviewingCarTxt: 'গাড়ি দেখা',
  eEnterYourVinTxt: ' আপনার VIN লিখুন',
  eRegistration: ' রেজিস্ট্রেশন নম্বর ',
  eVIN: ' VIN নম্বর',
  ePleaseFillInAllSectionsTxt: ' দেখার আগে সমস্ত বিভাগগুলি পূরণ করুন',
  eIncompleteDataTxt: 'অসম্পূর্ণ তথ্য',

  eReport: 'রিপোর্ট',
  eEmailOrPhoneTxt: 'ইমেইল অথবা ফোন',
  ePleaseSigninToContinueTxt: 'দয়া করে সাইন ইন করে সামনে এগিয়ে যান...',
  ePleaseSignupToContinueTxt: 'দয়া করে সাইন আপ করে সামনে এগিয়ে যান...',
  ePasswordTxt: 'পাসওয়ার্ড',
  eForgottenPasswordTxt: 'আপনি কি পাসওয়ার্ড ভুলে গেছেন?',
  eUseBiometricsTxt: 'বায়োমেট্রিক্স ব্যবহার করুন',
  eUseFaceIDTxt: 'ফেস-আইডি ব্যবহার করুন',
  eDarkThemeTxt: 'ডার্ক থিম',
  eLanguageTxt: 'ভাষা',
  eSignUpTxt: 'নিবন্ধন করুন',
  eNotAccountYetTxt: 'অ্যাকাউন্ট নেই?',
  ePhoneTxt: 'ফোন',
  eNameTxt: 'নাম',
  eUserNameTxt: 'ইউজার নাম',
  eEmailTxt: 'ই-মেইল',
  eConfirmPasswordTxt: 'পাসওয়ার্ড পুনরায় টাইপ করুন',
  eAlreadyAccountYetTxt: 'ইতিমধ্যে একটি একাউন্ট আছে?',
  eOtpVerifyTxt: 'Otp যাচাই করুন',
  eVerificationTxt: 'যাচাইকরণ ',
  eEnterOtpTxt: 'আপনার কোড নম্বর লিখুন',
  eOtpNotReceiveTxt: 'আপনি কোন কোড পাননি?',
  eResendNewCodeTxt: 'নতুন কোড আবার পাঠান',
};
